### ISSUE TITLE
A bunch of errors can't compile successfully. . . .

### ISSUE THREAD

**Issue by endbor3** [dhanax26/Apex-Legends-Offset-Dumper#5]
A bunch of errors can't compile successfully. . . .

**Comment by dhanax26** [comment]
Usually compiler errors are caused by using wrong visual studio settings,  set c++ ver to c++17 or latest and msvc to latest ver and x64 that should be enough, anyways if you could provide your output would be more easy to help you. btw this issue its from 8 days ago so ill asume you already solved this, have a good day.
